### ISSUE TITLE
Your repo has no issue

### ISSUE THREAD

**Issue by asadamatic** [Safdar-Nazir/OnBoarding-Screens#3]
Your repo does not have any issue(I didn't try to run it), try messing up with the code, so I can recommend you to improve it in the next issue.
![Completed](https://user-images.githubusercontent.com/37589169/103099988-6878fa00-4632-11eb-8aa3-264712420a91.png)

**Comment by Safdar-Nazir** [comment]
I will mess up my code very soon.

**Comment by asadamatic** [comment]
I'm done with messing up you code, just accept my pull request and you'll see.
